### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Hayabusa636** [1337Nexo/simple-recovery#5]
I get these errors when building
Build started...
1>------ Build started: Project: ImGui, Configuration: Debug x64 ------
1>imgui_impl_dx11.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'backends\imgui_impl_dx11.cpp': No such file or directory
1>imgui_impl_win32.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'backends\imgui_impl_win32.cpp': No such file or directory
1>imgui.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'imgui.cpp': No such file or directory
1>imgui_demo.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'imgui_demo.cpp': No such file or directory
1>imgui_draw.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'imgui_draw.cpp': No such file or directory
1>imgui_tables.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'imgui_tables.cpp': No such file or directory
1>imgui_widgets.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'imgui_widgets.cpp': No such file or directory
1>imgui_stdlib.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'misc\cpp\imgui_stdlib.cpp': No such file or directory
1>Generating Code...
1>Done building project "ImGui.vcxproj" -- FAILED.
2>------ Build started: Project: BigBaseV2, Configuration: Debug x64 ------
2>common.cpp
2>C:(location)\BigBaseV2\src\common.hpp(50,10): fatal error C1083: Cannot open include file: 'fmt/format.h': No such file or directory
2>Done building project "BigBaseV2.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 2 up-to-date, 0 skipped ==========

**Comment by fangshun2004** [comment]
It looks like your "imgui" subroutine isn't fully acquired

**Comment by fangshun2004** [comment]
There is also "fmblib"

**Comment by Hayabusa636** [comment]
> It looks like your "imgui" subroutine isn't fully acquired
> There is also "fmblib"
Can you tell me how to fix?

**Comment by fangshun2004** [comment]
Make sure that the appropriate subroutine project source code is available in the vendor directory if there is no need to get it again

**Comment by fangshun2004** [comment]
Make sure that there is the appropriate subroutine project source code in the vendor directory. If there is no project source code, it needs to be re-obtained

**Comment by 1337Nexo** [comment]
![image](https://user-images.githubusercontent.com/58114964/149003147-0ef75f2a-4e2e-419c-a6cb-f4cfd3a1b92f.png)
